set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENDED ON)

find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
  message(STATUS "Found ccache, will leverage to reduce build times")
  set(CMAKE_CXX_COMPILER_LAUNCHER ccache)
  set(CMAKE_CC_COMPILER_LAUNCHER ccache)
endif()

set(CMAKE_BUILD_TYPES "" None Debug Release RelWithDebInfo)
set(CMAKE_BUILD_TYPE Debug CACHE STRING "Type of build: ${CMAKE_BUILD_TYPES}")
set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS ${CMAKE_BUILD_TYPES})
if(NOT CMAKE_BUILD_TYPE IN_LIST CMAKE_BUILD_TYPES)
  message(FATAL_ERROR "CMAKE_BUILD_TYPE should be one of ${CMAKE_BUILD_TYPES}")
endif()