name: C/C++ CI

on:
  push:
    branches:
    - "**"      # Run on all branches
    - "!main"   # Except main (branches should pass before being merged into main anyways)
  pull_request:
    branches:
    - "**"
    - "!main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
